import './globals.css'
import Header from "./components/Header";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook</title>
      </Head>

      <Header />
      
      <main>
        {/* Sidebar */}
        {/* Feed */}
        {/* Widgets */}
      </main>
    </div>
  );
}1

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
